Table:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: commitMessage
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: commitMessage
        KeyType: RANGE

    ProvisionedThroughput:
      ReadCapacity: ${self:custom.dbReadCapacityUnits}
      WriteCapacity: ${self:custom.dbWriteCapacityUnits}
