service: lambda-environment
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  # de acordo com o stage, nós definimos qual ambiente será utilizado
  stage: ${opt:stage, "qa"}
  environment: ${file(./config/env.${self:provider.stage}.json)}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
